---
- hosts: linux
  user: raj
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  tasks:
  - name: install telnet and lynx
    yum: pkg={{ item }} state=latest
    with_items:
    - telnet
    - lynx
    tags:
     - packages
  - name: verify if telnet is installed or not
    raw: yum list installed | grep telnet > ./logs.log
    tags: 
     - logging


  
