---
- hosts: linux
  user: raj
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: no
  tasks:
  - name: installing apache tomcat
    action: yum name=tomcat state=installed
    wait_for:
     port: 8080
     state: started
  - name: verifyign lynx installation
     yum: pkg=lynx state=present updatecache=true

